/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5651f025-2a00-4d04-a1b4-91ba31b8756b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_gljBMlstN",
    "aws_user_pools_web_client_id": "7drc32j9olt7ka3abtsp1ppns7",
    "oauth": {}
};


export default awsmobile;
